services:
  - type: web
    name: tcs-clothing-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://phani200656_db_user:c97Vy27n24eCak4w@cluster3.yidfxrd.mongodb.net/tcs-store?retryWrites=true&w=majority
      - key: JWT_SECRET
        value: tcs_super_secret_jwt_key_2026
      - key: ADMIN_EMAIL
        value: admin@tcs.com
      - key: ADMIN_PASSWORD
        value: Admin@123
      - key: CLIENT_URL
        value: https://cloth-sh.vercel.app
